# Generated by Django 3.0.8 on 2020-07-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndPoints',
            new_name='Endpoint',
        ),
    ]
